### ISSUE TITLE
ValueError: Expected 2D array, got 1D array instead:

### ISSUE THREAD

**Issue by Mar-Gra-creator** [Gardner-BinfLab/PPI_Analysis_2022#1]
hey
Yesterday everything works fine :)

Today:

```
(ppi) marcin@marcin-B550-AORUS-ELITE-AX-V2:~/PPI_Analysis_2022/script$ python rf.py -a lpg_effectors_genes_BUCHRISIER-short.fasta -p effectors_genes_BUCHRISIER_pairs.txt -c lazypair_clfs.pickle -t 16 > lpg_effectors_genes_BUCHRISIER_interactions.tsv
Traceback (most recent call last):
  File "rf.py", line 272, in <module>
    main()
  File "rf.py", line 194, in main
    print(predict(clfs, s1, pr, ids, ids))
  File "rf.py", line 135, in predict
    preds = pd.DataFrame([clf.predict_proba(df.AAindex_mean.tolist())[:,1] for clf in clfs]).T
  File "rf.py", line 135, in <listcomp>
    preds = pd.DataFrame([clf.predict_proba(df.AAindex_mean.tolist())[:,1] for clf in clfs]).T
  File "/home/marcin/anaconda3/envs/ppi/lib/python3.8/site-packages/sklearn/ensemble/_forest.py", line 850, in predict_proba
    X = self._validate_X_predict(X)
  File "/home/marcin/anaconda3/envs/ppi/lib/python3.8/site-packages/sklearn/ensemble/_forest.py", line 579, in _validate_X_predict
    X = self._validate_data(X, dtype=DTYPE, accept_sparse="csr", reset=False)
  File "/home/marcin/anaconda3/envs/ppi/lib/python3.8/site-packages/sklearn/base.py", line 566, in _validate_data
    X = check_array(X, **check_params)
  File "/home/marcin/anaconda3/envs/ppi/lib/python3.8/site-packages/sklearn/utils/validation.py", line 769, in check_array
    raise ValueError(
ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

```

I reinstalled it several timess...

pls help, cheers

**Comment by lcscs12345** [comment]
Hi @Mar-Gra-creator,

Thanks for reporting the error. Is the error reproducible? Have you have tried using the same input files that worked for you yesterday?

Cheers,
Lim
